spring.application.name=BnBillains
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
spring.datasource.hikari.maximum-pool-size=10

#Encoding
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#Guardar_Imagenes
UPLOAD_PATH=uploads


#OAUTH GOOGLE

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email, profile


# --- LINKEDIN---
#spring.security.oauth2.client.registration.linkedin.client-id=${LINKEDIN_ID}
#spring.security.oauth2.client.registration.linkedin.client-secret=${LINKEDIN_SECRET}
#spring.security.oauth2.client.registration.linkedin.scope=openid, profile, email
#spring.security.oauth2.client.registration.linkedin.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.linkedin.redirect-uri={baseUrl}/login/oauth2/code/linkedin
# Como no es estándar, hay que definir los proveedores:
#spring.security.oauth2.client.provider.linkedin.authorization-uri=https://www.linkedin.com/oauth/v2/authorization
#spring.security.oauth2.client.provider.linkedin.token-uri=https://www.linkedin.com/oauth/v2/accessToken
#spring.security.oauth2.client.provider.linkedin.jwk-set-uri=https://www.linkedin.com/oauth/openid/jwks
#spring.security.oauth2.client.provider.linkedin.user-info-uri=https://api.linkedin.com/v2/userinfo
#spring.security.oauth2.client.provider.linkedin.user-name-attribute=sub


# GITLAB OAUTH2

spring.security.oauth2.client.registration.gitlab.client-id=${GITLAB_CLIENT_ID}
spring.security.oauth2.client.registration.gitlab.client-secret=${GITLAB_CLIENT_SECRET}
spring.security.oauth2.client.registration.gitlab.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.gitlab.scope=read_user,openid,profile,email
spring.security.oauth2.client.registration.gitlab.client-name=GitLab

spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com
spring.security.oauth2.client.provider.gitlab.authorization-uri=https://gitlab.com/oauth/authorize
spring.security.oauth2.client.provider.gitlab.token-uri=https://gitlab.com/oauth/token
spring.security.oauth2.client.provider.gitlab.user-info-uri=https://gitlab.com/api/v4/user

spring.security.oauth2.client.provider.gitlab.user-name-attribute=email

